server {
    listen 80;
    server_name _;

    root /var/www/html/public;
    index index.html index.php;

    # Docker DNS для резолву сервісу php під час виконання запитів.
    resolver 127.0.0.11 ipv6=off;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~ ^/api/(.+\.php)$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html/php/api/$1;
        fastcgi_param PATH_INFO /$1;
        set $php_upstream php:9000;
        fastcgi_pass $php_upstream;
    }
}
